// Generated by CoffeeScript 1.4.0
(function() {
  var Bot, Pitboss, fs, request, retrieveBot, util, vm,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  request = require('request');

  util = require('util');

  vm = require('vm');

  Pitboss = require('pitboss').Pitboss;

  Bot = (function() {

    function Bot(opts) {
      var _base;
      this.opts = opts;
      this.setupFinished = __bind(this.setupFinished, this);

      this.opts || (this.opts = {});
      this.name = this.opts['name'] || "Unnamed";
      (_base = this.opts)['brainSize'] || (_base['brainSize'] = 4096);
      this.brain = {};
      this.loaded = false;
    }

    Bot.prototype.getOptions = function(code, callback) {
      var myCode, nameFetcher,
        _this = this;
      myCode = "var module = {};\nvar exports = module.exports = {};\n" + code + ";\nvar result = {};\n \nvar checkAndAssign = function (func) {\n  if (func !== undefined && typeof func == 'function') { \n     return func();\n  }\n  return null;\n}\n \nresult.name = checkAndAssign(exports.name);\nresult.debug = checkAndAssign(exports.debug);\n \nresult";
      nameFetcher = new Pitboss(myCode);
      return nameFetcher.run({}, function(err, result) {
        if (err) {
          console.log(err);
        }
        if (((result != null ? result.name : void 0) != null)) {
          _this.name = result.name || _this.name;
        }
        if (((result != null ? result.debug : void 0) != null)) {
          _this.debug = result.debug || _this.debug;
        }
        return callback();
      });
    };

    Bot.prototype.setupFinished = function() {
      this.loaded = true;
      return typeof this.loadedCallback === "function" ? this.loadedCallback(this) : void 0;
    };

    Bot.prototype.setup = function(code) {
      this.getOptions(code, this.setupFinished);
      code = "// Debug setup\nvar debug = [];\nvar console = {};\nconsole.log = function(txt){debug.push(txt)};\n\n// CommonJS compat\nvar module = {};\nvar exports = module.exports = {};\n" + code + ";\nvar result = {}\nvar bet = exports.play(game);\nresult = {\n  bet: bet,\n  brain: game.self.brain,\n  debug: debug\n}\nresult // Return results to Pitboss";
      return this.player = new Pitboss(code, this.opts);
    };

    Bot.prototype.update = function(game, callback) {
      var startTime,
        _this = this;
      if ((this.opts.debug != null)) {
        startTime = Date.now();
      }
      game.self.brain = this.brain;
      return this.player.run({
        game: game
      }, function(err, result) {
        var debug, _i, _len, _ref;
        if ((_this.opts.debug != null)) {
          console.log("Execution of \"" + _this.name + "\" took " + (Date.now() - startTime) + " ms.");
        }
        if (err) {
          return callback(err);
        } else {
          if (_this.opts['debug']) {
            _ref = result['debug'];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              debug = _ref[_i];
              console.log(util.inspect(debug, false, 6));
            }
          }
          _this.saveBrain(result['brain']);
          return typeof callback === "function" ? callback(null, result['bet']) : void 0;
        }
      });
    };

    Bot.prototype.saveBrain = function(brainObj) {
      var length;
      length = JSON.stringify(brainObj || {});
      if (length > this.opts['brainSize']) {
        return this.brain = {};
      } else {
        return this.brain = brainObj;
      }
    };

    return Bot;

  })();

  exports.create = function(id, opts, callback) {
    var bot;
    bot = new Bot(opts);
    bot.loadedCallback = callback;
    console.log("Creating bot for - " + id);
    retrieveBot(id, function(err, code) {
      return bot.setup(code);
    });
    return bot;
  };

  retrieveBot = function(id, callback) {
    if (id.match(/^http/)) {
      return request(id, function(err, response, body) {
        if (err) {
          return typeof callback === "function" ? callback(err) : void 0;
        } else {
          return typeof callback === "function" ? callback(null, body.toString()) : void 0;
        }
      });
    } else {
      return fs.readFile(id, function(err, data) {
        if (err) {
          return typeof callback === "function" ? callback(err) : void 0;
        } else {
          return typeof callback === "function" ? callback(null, data.toString()) : void 0;
        }
      });
    }
  };

}).call(this);
