// Generated by CoffeeScript 1.6.3
(function() {
  var Bot, LocalBot, crypto, fs, request, retrieveBot, tmpDir, util,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fs = require('fs');

  request = require('request');

  util = require('util');

  crypto = require('crypto');

  Bot = require('./bot').Bot;

  tmpDir = __dirname + "/../../tmp";

  exports.Bot = LocalBot = (function(_super) {
    __extends(LocalBot, _super);

    function LocalBot(opts) {
      this.opts = opts;
      this.setupFinished = __bind(this.setupFinished, this);
      this.opts || (this.opts = {});
      if (this.opts.debug) {
        this.debug = true;
      }
      this.loaded = false;
    }

    LocalBot.prototype.setup = function(module) {
      this.player = module;
      this.playerInfo = module.info || {};
      this.name = this.playerInfo.name || "Unnamed";
      return this.setupFinished();
    };

    LocalBot.prototype.setupFinished = function(err) {
      this.loaded = true;
      return this.emit('loaded');
    };

    LocalBot.prototype.update = function(game, callback) {
      var result, startTime;
      if (this.debug) {
        startTime = Date.now();
      }
      result = this.player.play(game);
      if (this.debug) {
        console.log("Execution of \"" + this.name + "\" took " + (Date.now() - startTime) + " ms.");
      }
      return setImmediate(function() {
        return callback(null, result);
      });
    };

    return LocalBot;

  })(Bot);

  exports.create = function(id, opts, callback) {
    var bot;
    if (arguments.length === 2) {
      callback = arguments[arguments.length - 1];
      opts = {};
    }
    bot = new LocalBot(opts);
    if (bot.debug) {
      console.log("Creating bot for - " + id);
    }
    retrieveBot(id, function(err, mod) {
      if (err) {
        throw err;
      }
      bot.setup(mod);
      return typeof callback === "function" ? callback(null, bot) : void 0;
    });
    return bot;
  };

  retrieveBot = function(id, callback) {
    var e, err, mod, name, shasum;
    mod = null;
    err = null;
    if (id.match(/^https?/)) {
      shasum = crypto.createHash('sha1');
      name = null;
      return request(id, function(err, response, body) {
        var fileName, filePath;
        fileName = shasum.update(body).digest('hex');
        filePath = "" + tmpDir + "/" + fileName;
        if (err) {
          return typeof callback === "function" ? callback(err) : void 0;
        } else {
          return fs.writeFile(filePath, body, function(err) {
            var e;
            try {
              mod = require(filePath);
            } catch (_error) {
              e = _error;
              err = e;
            }
            return callback(err, mod);
          });
        }
      });
    } else {
      try {
        mod = require("" + (process.cwd()) + "/" + id);
      } catch (_error) {
        e = _error;
        err = e;
      }
      return callback(err, mod);
    }
  };

}).call(this);
