// Generated by CoffeeScript 1.4.0
(function() {
  var fs, inspect;

  inspect = require('util').inspect;

  fs = require('fs');

  module.exports = function(filename) {
    var buffers, ready, stream, write;
    buffers = [];
    ready = false;
    stream = fs.createWriteStream("" + (process.cwd()) + "/" + filename);
    console.log(stream);
    stream.once('open', function() {
      console.log("READY");
      return ready = true;
    });
    write = function(data) {
      var buffer, _i, _len;
      if (ready) {
        for (_i = 0, _len = buffers.length; _i < _len; _i++) {
          buffer = buffers[_i];
          stream.write(buffer);
        }
        return stream.write(data);
      } else {
        return buffers.push(data);
      }
    };
    return {
      complete: function(game) {
        if (game.state === 'complete') {
          return write("" + (inspect(game, false, 6)) + "\n\n");
        }
      }
    };
  };

}).call(this);
