// Generated by CoffeeScript 1.6.3
(function() {
  var inspect;

  inspect = require('util').inspect;

  exports.complete = function(status) {
    if (status.state === 'complete') {
      return process.stdout.write("\n" + (inspect(status, false, 6)) + "\n");
    }
  };

}).call(this);
