// Generated by CoffeeScript 1.3.3
(function() {
  var round;

  round = 0;

  exports.complete = function(status) {
    console.log("Round #" + round + " complete");
    console.log(status.players.map(function(p) {
      return "" + p.name + " - $" + p.chips;
    }));
    return round++;
  };

}).call(this);
